apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mini-anomaly-ingress
  namespace: mini-anomaly
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: mini-anomaly.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mini-anomaly-svc
                port:
                  number: 80
