apiVersion: v1
kind: Service
metadata:
  name: mini-anomaly-svc
  namespace: mini-anomaly
spec:
  type: NodePort
  selector:
    app: mini-anomaly
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32080
